---
- name: Make sure services/config/photoprism exists
  file:
    path: "{{ appdata_dir }}/photoprism"
    state: directory
    owner: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"
  become: yes

- name: Make sure docker-compose.yml is in place.
  template:
    src: templates/docker-compose.yml
    dest: "{{ appdata_dir }}/photoprism"
    owner: "{{ docker_user.name }}"
    mode: "{{ docker_compose_file_mask }}"
    validate: docker-compose -f %s config
  notify:
    - "photoprism : pulling docker image"
    - "photoprism : starting docker container"
  become: yes
