---
# tasks file for gitea

- name: Make sure services/config/haste-server exists
  file:
    path: "{{ appdata_dir }}/haste-server"
    state: directory
  become: yes

- name: Make sure docker-compose.yml is in place.
  template:
    src: files/docker-compose.yml
    dest: "{{ appdata_dir }}/haste-server"
    force: no
  notify:
    - pulling docker image
    - starting docker container
  become: yes

- name: Start docker container.
  community.docker.docker_compose:
    project_src: "{{ ansible_env.HOME  }}/services/config/haste-server/"
  become: yes
