---
- name: Make sure services/config/haste-server exists
  file:
    path: "{{ appdata_dir }}/haste-server"
    state: directory
  become: yes

- name: Make sure docker-compose.yml is in place.
  template:
    src: files/docker-compose.yml
    dest: "{{ appdata_dir }}/haste-server"
    validate: docker-compose -f %s config
  notify:
    - "haste-server : pulling docker image"
    - "haste-server : starting docker container"
  become: yes
