---
version: "2.1"
services:
  radarr:
    image: linuxserver/radarr:amd64-latest
    container_name: radarr
    environment:
      - PUID={{ radarr_uid }}
      - PGID={{ radarr_gid }}
      - TZ={{ TZ }}
    volumes:
      - ./radarr:/config
      - "{{ movies_dir }}:/movies"
      - "{{ cache_dir }}/downloads:/downloads"
    ports:
      - "{{ radarr_port }}:7878"
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:amd64-latest
    container_name: sonarr
    environment:
      - PUID={{ sonarr_uid }}
      - PGID={{ sonarr_gid }}
      - TZ={{ TZ }}
    volumes:
      - "./sonarr:/config"
      - "{{ series_dir }}:/tv"
      - "{{ cache_dir }}/downloads:/downloads"
    ports:
      - "{{ sonarr_port }}:8989"
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr:amd64-latest
    container_name: bazarr
    environment:
      - PUID={{ bazarr_uid }}
      - PGID={{bazarr_gid }}
      - TZ=America/Argentina/Cordoba
    volumes:
      - "./bazarr:/config"
      - "{{ movies_dir }}:/movies"
      - "{{ series_dir }}:/tv"
    ports:
      - "{{ bazarr_port }}:6767"
    restart: unless-stopped

  ombi:
    image: linuxserver/ombi:4.7.0
    container_name: ombi
    environment:
      - PUID={{ ombi_uid }}
      - PGID={{ ombi_gid }}
      - TZ={{ TZ }}
    volumes:
      - "./ombi/config:/config"
    ports:
      - "{{ ombi_port }}:3579"
    restart: unless-stopped

  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID={{ prowlarr_uid }}
      - PGID={{ prowlarr_gid }}
      - TZ={{ TZ }}
    volumes:
      - "./prowlarr/prowlarr:/config"
    ports:
      - "{{ prowlarr_port }}:9696"
    restart: unless-stopped

  unmanic-movies:
    container_name: unmanic-movies
    image: josh5/unmanic:latest
    ports:
      - "{{ unmanic_port_movies }}:8888"
    environment:
      - PUID={{ unmanic_uid }}
      - PGID={{ unmanic_gid }}
      - TZ={{ TZ }}
    volumes:
      - "./unmanic/movies/movies/unmanic:/config"
      - "{{ movies_dir }}:/library"
      - "{{ cache_dir }}/movies:/tmp/unmanic"
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped

  unmanic-series:
    container_name: unmanic-series
    image: josh5/unmanic:latest
    ports:
      - "{{ unmanic_port_series }}:8888"
    environment:
      - PUID={{ unmanic_uid }}
      - PGID={{ unmanic_gid }}
      - TZ={{ TZ }}
    volumes:
      - "./unmanic/series/series/unmanic:/config"
      - "{{ series_dir }}:/library"
      - "{{ cache_dir }}/series:/tmp/unmanic"
    devices:
      - /dev/dri:/dev/dri
    restart: unless-stopped
