---
version: "3"

networks:
  default:
    external: false
  gitea:
    external: false

services:
  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
     - USER_UID={{ gitea_uid }}
     - USER_GID={{ gitea_gid }}
     - GITEA__database__DB_TYPE={{ gitea_database_type }}
     - GITEA__database__HOST=db:5432
     - GITEA__database__NAME={{ gitea_database_name  }}
     - GITEA__database__USER={{ gitea_database_user  }}
     - GITEA__database__PASSWD={{ gitea_database_name  }}
    volumes:
      - ./gitea/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "{{ gitea_webport }}:3000"
      - "{{ gitea_sshport }}:22"
    networks:
      - gitea
    depends_on:
      - db
    restart: always

  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER={{ gitea_database_user }}
      - POSTGRES_PASSWORD={{ gitea_database_user }}
      - POSTGRES_DB={{ gitea_database_password }}
    networks:
      - gitea
    volumes:
      - ./gitea/postgres:/var/lib/postgresql/data


  drone:
    image: drone/drone:latest
    ports:
      - "{{ drone_port }}:80"
    environment:
      - DRONE_SERVER_HOST={{ drone_domain }}
      - DRONE_SERVER_PROTO=https
      - DRONE_RPC_SECRET={{drone_rpc_secret}}
      - DRONE_GITEA_CLIENT_ID={{ drone_client_id }}
      - DRONE_GITEA_CLIENT_SECRET={{ drone_secret_id }}
      - DRONE_GITEA_SERVER=https://{{ gitea_domain }}
      - DRONE_LOGS_DEBUG=true
      - DRONE_CRON_DISABLED=true
    volumes:
      - ./drone/data:/data
    networks:
      - gitea
      - default

  runner:
    image: drone/drone-runner-docker:latest
    environment:
      - DRONE_RPC_HOST={{ drone_domain }}
      - DRONE_RPC_PROTO=https
      - DRONE_RPC_SECRET={{ drone_rpc_secret }}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - default
      - gitea
