---
# Tasks for docker role.
# This role will:
#   - Install Docker.
#   - Open endpoint of Docker.
#   - Install docker-compose

- name: Ensure python3 and pip3 is installed.
  package:
    name:
      - python3
      - python3-pip
    state: present
  become: yes

- name: Install docker-compose via pip3.
  pip:
    name: docker-compose
    state: present
  become: yes
