---
- name: pulling docker image
  shell:
    chdir: "{{appdata_dir}}/paperless"
    cmd: "docker-compose pull"
  become: true

- name: starting docker container
  shell:
    chdir: "{{appdata_dir}}/paperless"
    cmd: "docker-compose up -d"
  become: true
