---
- name: pulling docker image
  shell:
    chdir: "{{appdata_dir}}/nextcloud"
    cmd: "docker-compose pull"
  become: true

- name: starting docker container
  shell:
    chdir: "{{appdata_dir}}/nextcloud"
    cmd: "docker-compose up -d"
  become: true
    
- name: restarting docker container
  shell:
    chdir: "{{appdata_dir}}/nextcloud"
    cmd: "docker-compose restart"
  become: true
