---
- name: Make sure services/config/qbittorrent exists
  file:
    path: "{{ appdata_dir }}/qbittorrent"
    state: directory
  become: yes

- name: Make sure docker-compose.yml is in place.
  template:
    src: templates/docker-compose.yml
    dest: "{{ appdata_dir }}/qbittorrent"
    validate: docker-compose -f %s config
  notify:
    - "qbittorrent : pulling docker image"
    - "qbittorrent : starting docker container"
  become: yes
