---
- name: Make sure services/config/duplicati exists
  file:
    path: "{{ appdata_dir }}/duplicati"
    owner: "{{ docker_user.name }}"
    mode: "{{ docker_compose_directory_mask }}"
    state: directory
  become: yes

- name: Make sure docker-compose.yml is in place.
  template:
    src: templates/docker-compose.yml
    dest: "{{ appdata_dir }}/duplicati"
    owner: "{{ docker_user.name }}"
    mode: "{{ docker_compose_file_mask }}"
    validate: docker-compose -f %s config
  notify:
    - "duplicati : pulling docker image"
    - "duplicati : starting docker container"
  become: yes

- name: Make sure nginx configurations installed.
  copy:
    src: "{{ item }}"
    dest: "{{ appdata_dir }}/duplicati"
    owner: "{{ docker_user.name }}"
    mode: "{{ docker_compose_file_mask }}"
    force: yes
  with_fileglob: "files/*.json"
  become: yes
  notify:
    - "duplicati : restarting docker container"
