---
version: "3"
services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: my-syncthing
    environment:
      - PUID={{ syncthing_uid }}
      - PGID={{ syncthing_gid }}
    volumes:
      - "{{ syncthing_dir }}:/var/syncthing"
    ports:
      - "{{ syncthing_port }}:8384"
      - 22000:22000/tcp
      - 22000:22000/udp
    restart: unless-stopped
