--- 
version: "3.3"

services:
  app:
    image: fireflyiii/core:latest
    restart: always
    volumes:
      - ./upload:/var/www/html/storage/upload
    env_file: .env
    ports:
      - "{{ firefly_port }}:8080"
    depends_on:
      - db
  db:
    image: mariadb    
    hostname: fireflyiiidb
    restart: always
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD={{ firefly_db_root_password }}
      - MYSQL_USER={{ firefly_db_user }}
      - MYSQL_PASSWORD={{ firefly_db_password }}
      - MYSQL_DATABASE={{ firefly_db_name }}
    volumes:
      - ./database:/var/lib/mysql
