---
- name: Make sure services/config/code-server exists
  file:
    path: "{{ appdata_dir }}/code-server"
    state: directory
  become: yes

- name: Make sure docker-compose.yml is in place.
  template:
    src: templates/docker-compose.yml
    dest: "{{ appdata_dir }}/code-server"
    validate: docker-compose -f %s config
  notify:
    - "code-server : pulling docker image"
    - "code-server : starting docker container"
  become: yes
